# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # box镜像
  config.vm.box = "MiMiKnight/ubuntu-22.04.4-server-amd64"
  # box版本
  config.vm.box_version = "1.0.0"
  # 公共Shell
  config.vm.provision "shell", path: "script/vm_public.sh"
  
  config.vm.define "master01" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "192.168.201.51",netmask: "24"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevMySQL"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "8192"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_master01.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end
  
  config.vm.define "master02" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "192.168.201.52",netmask: "24"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevMariaDB"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "4096"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_master02.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end
  
  config.vm.define "master03" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "192.168.201.53",netmask: "24"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevRedis"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "4096"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_master03.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end

  config.vm.define "work01" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "192.168.201.54",netmask: "24"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevNacos"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "12288"
      # cpu
      vb.cpus = 8
    end
    # shell
    host.vm.provision "shell", path: "script/vm_node01.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end

  config.vm.define "work02" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "192.168.201.55",netmask: "24"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevNacos"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "12288"
      # cpu
      vb.cpus = 8
    end
    # shell
    host.vm.provision "shell", path: "script/vm_node02.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end

  config.vm.define "work03" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "192.168.201.56",netmask: "24"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevNacos"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "12288"
      # cpu
      vb.cpus = 8
    end
    # shell
    host.vm.provision "shell", path: "script/vm_node03.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end
  
end
