# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # box镜像
  config.vm.box = "MiMiKnight/ubuntu-22.04.4-server-amd64"
  # box版本
  config.vm.box_version = "1.0.0"
  # 公共Shell
  config.vm.provision "shell", path: "script/ubuntu22.04.4_jammy_source.sh"
  config.vm.provision "shell", path: "script/vm_public.sh"
  
  config.vm.define "master01" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.2.1",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevMySQL"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "8192"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_master01.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end
  
  config.vm.define "master02" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.2.2",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevMariaDB"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "4096"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_master02.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end
  
  config.vm.define "master03" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.2.3",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevRedis"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "4096"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_master03.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end

  config.vm.define "worker01" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.2.4",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevNacos"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "12288"
      # cpu
      vb.cpus = 8
    end
    # shell
    host.vm.provision "shell", path: "script/vm_worker01.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end

  config.vm.define "worker02" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.2.5",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevNacos"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "12288"
      # cpu
      vb.cpus = 8
    end
    # shell
    host.vm.provision "shell", path: "script/vm_worker02.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end

  config.vm.define "worker03" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.2.6",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevNacos"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "12288"
      # cpu
      vb.cpus = 8
    end
    # shell
    host.vm.provision "shell", path: "script/vm_worker03.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
  end
  
end
