apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx # 打标签（此处一般与容器同名）
  name: nginx-deployment # deployment的名称
  namespace: backend # 指定命名空间
spec:
  replicas: 2   # pod数量
  selector:
    matchLabels:
      app: nginx # 选择指定的标签
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: harbor.devops.vm.mimiknight.cn/libray/nginx:1.27.0  # 镜像
        name: nginx  # 容器名称
        imagePullPolicy: IfNotPresent # 镜像pull策略
        ports:
        - containerPort: 80  # 容器对外暴露的端口号
        volumeMounts:  # 数据卷挂载
        - name: conf  # 指定数据卷名称
          mountPath: /etc/nginx/nginx.conf  # 数据在容器中的路径
        - name: log
          mountPath: /var/log/nginx
        - name: html
          mountPath: /etc/nginx/html
      tolerations:  # 容忍度配置
      - key: "key"
        operator: "Equal"
        value: "nginx"
        effect: "NoSchedule"
      volumes:  # 数据卷定义
      - name: conf  # 数据卷名称
        hostPath:
          path: /Users/w/kube/nginx/conf/nginx.conf  # 数据在宿主机的路径
      - name: log
        hostPath:
          path: /Users/w/kube/nginx/logs
          type: Directory  # 文件夹类型
      - name: html
        hostPath:
          path: /Users/w/kube/nginx/html
          type: Directory