# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # box镜像
  config.vm.box = "MiMiKnight/ubuntu-24.04-server-amd64"
  # box版本
  config.vm.box_version = "1.0.0"
  # 公共Shell
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get install -y wget
    sudo cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.bak
    sudo sed -i "s@http://.*archive.ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list.d/ubuntu.sources
    sudo sed -i "s@http://.*security.ubuntu.com@http://repo.huaweicloud.com@g" /etc/apt/sources.list.d/ubuntu.sources
    sudo apt-get update
    sudo apt-get dist-upgrade -y
    sudo apt-get autoremove
    sudo apt-get autoclean
    sudo apt-get install -y \
      vim iputils-ping net-tools lrzsz gcc \
      ntp ntpdate gdisk telnet
    sudo ntpdate ntp.vm.mimiknight.cn
    sudo echo "Run common shell finished !!!"
  SHELL
  
  config.vm.define "jenkins" do |jenkins|
    # OnlyHost网卡
    jenkins.vm.network "private_network", ip: "192.168.200.1",netmask: "24"
    # provider
    jenkins.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevOpsJenkins"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "4096"
      # cpu
      vb.cpus = 2
    end
    # shell
    jenkins.vm.provision "shell", inline: <<-SHELL
      sudo hostnamectl hostname jenkins.devops.vm.mimiknight.cn
      sudo echo "Install Jenkins VM finished !!!"
    SHELL
  end
  
  config.vm.define "harbor" do |harbor|
    # OnlyHost网卡
    harbor.vm.network "private_network", ip: "192.168.200.2",netmask: "24"
    # provider
    harbor.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "DevOpsHarbor"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "8192"
      # cpu
      vb.cpus = 4
    end
    # shell
    harbor.vm.provision "shell", inline: <<-SHELL
      sudo hostnamectl hostname harbor.devops.vm.mimiknight.cn
      sudo echo "Install Harbor VM finished !!!"
    SHELL
  end
  
end
