# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # box镜像
  config.vm.box = "MiMiKnight/ubuntu-22.04.4-server-amd64"
  # box版本
  config.vm.box_version = "1.0.0"
  # 公共Shell
  config.vm.provision "shell", path: "script/ubuntu_source.sh"
  config.vm.provision "shell", path: "script/vm_public.sh"

  # mysql.devops.vm.mimiknight.cn
  config.vm.define "mysql" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.1.1",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "xxx"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "1024"
      # cpu
      vb.cpus = 2
    end
    # shell
    host.vm.provision "shell", path: "script/vm_mysql.sh"
    host.vm.provision "shell", path: "script/install_mysql_using_ded.sh"
  end

  # jenkins.devops.vm.mimiknight.cn
  config.vm.define "jenkins" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.1.2",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "xxx"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "2048"
      # cpu
      vb.cpus = 2
    end
    # shell
    host.vm.provision "shell", path: "script/vm_jenkins.sh"
  end

  # harbor.devops.vm.mimiknight.cn
  config.vm.define "harbor" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.1.3",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    host.vm.disk :disk, size: "500GB", name: "box-disk002", primary: false
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "xxx"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "8192"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_harbor.sh"
    host.vm.provision "shell", path: "script/lvm_extend.sh"
    host.vm.provision "shell", path: "script/install_docker.sh"
    host.vm.provision "shell", path: "script/install_harbor.sh"
  end

  # kuboard.devops.vm.mimiknight.cn
  config.vm.define "kuboard" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.101.1.4",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "xxx"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "2048"
      # cpu
      vb.cpus = 2
    end
    # shell
    host.vm.provision "shell", path: "script/vm_kuboard.sh"
    host.vm.provision "shell", path: "script/install_docker.sh"
    host.vm.provision "shell", path: "script/install_kuboard.sh"
  end
  
end
