# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # box镜像
  config.vm.box = "MiMiKnight/ubuntu-22.04.4-server-amd64"
  # box版本
  config.vm.box_version = "1.0.0"
  # 公共Shell
  config.vm.provision "shell", path: "script/ubuntu_source.sh"
  config.vm.provision "shell", path: "script/vm_public.sh"
  # 关闭默认共享文件夹
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # 新增share共享文件夹
  config.vm.synced_folder "share/", "/opt/share", owner: "vagrant", group: "vagrant"

  # harbor.explore.vm.mimiknight.cn
  config.vm.define "harbor" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.103.1.1",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "xxx"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "4096"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_harbor.sh"
    host.vm.provision "shell", path: "script/install_docker.sh"
  end

  # panda.explore.vm.mimiknight.cn
  config.vm.define "panda" do |host|
    # OnlyHost网卡
    host.vm.network "private_network", ip: "10.103.1.2",netmask: "16"
    # Disk
    host.vm.disk :disk, size: "65GB", name: "box-disk001", primary: true
    # provider
    host.vm.provider "virtualbox" do |vb|
      # 虚拟机名称
      #vb.name = "xxx"
      # 图形化
      vb.gui = false
      # 内存
      vb.memory = "4096"
      # cpu
      vb.cpus = 4
    end
    # shell
    host.vm.provision "shell", path: "script/vm_panda.sh"
    #host.vm.provision "shell", path: "script/install_docker.sh"
  end
  
end
